CREATE TABLE "events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"start_date_time" timestamp with time zone NOT NULL,
	"end_date_time" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "valid_date_range" CHECK ("events"."end_date_time" >= "events"."start_date_time")
);
--> statement-breakpoint
CREATE INDEX "start_date_time_idx" ON "events" USING btree ("start_date_time");--> statement-breakpoint
CREATE INDEX "end_date_time_idx" ON "events" USING btree ("end_date_time");